# Blocked Server(s) :
blocked-servers:
  - "Auth"
# Blocked Command(s) :
blocked-commands:
  - "server"
  - "send"
  - "connect"
# Error Message :
error-message: "&cYou cannot use this command on this player!"
# /send all (Server) Error Message :
all-players-message: "&aSent {AMOUNT_OF_PLAYERS} players to {SERVER}, &eExcept {AMOUNT_OF_PLAYERS_IN_BLOCKED_SERVER} players which were in a blocked server."